name: mapdescriptor
description: Convert TimeStamp values to strings and vice versa in a given Map of key-value pairs. 
version: 1.0.4
repository: https://github.com/KBM90/mapdescriptor

environment:
  sdk: '>=2.19.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
